name: build

on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x.x
    
    - name: Dotnet Installation Info
      run: dotnet --info
    
    - name: Build
      run: dotnet build
    
    - name: Test
      run: dotnet test --no-build --logger trx --results-directory "TestResults-${{ matrix.platform }}"

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-test-results-${{ matrix.platform }}
        path: TestResults-${{ matrix.platform }}
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}